name: stryderx
services:
  stryderx:
    build:
      context: ..
      dockerfile: stryderx_docker/Dockerfile.dev
      args:
        - APP_VERSION=${APP_VERSION:-dev}
        - GIT_COMMIT=${GIT_COMMIT:-unknown}
        - BUILD_DATE=${BUILD_DATE:-unknown}
        - ROS_DISTRO=${ROS_DISTRO}
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
    image: stryderx:${APP_VERSION:-dev}
    container_name: stryderx-robot
    volumes:
      - ../:/home/rpi/stryderx/ # Base Image robot-base-docker username is RPi.
      - /dev/bus/usb:/dev/bus/usb # Required for camera controls like exposure/autofocus
    group_add:
      - video
    devices:
      - "/dev/video0:/dev/video0"
    tty: true
    stdin_open: true
    command: /bin/bash
    network_mode: host
