name: stryderx
services:
  stryderx:
    build:
      context: ..
      dockerfile: stryderx_docker/Dockerfile
      args:
        - APP_VERSION=${APP_VERSION:-dev}
        - GIT_COMMIT=${GIT_COMMIT:-unknown}
        - BUILD_DATE=${BUILD_DATE:-unknown}
        - ROS_DISTRO=${ROS_DISTRO}
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
    image: stryderx:${APP_VERSION:-dev}
    volumes:
      - ../src:/home/rpi/stryderx/src # Base Image robot-base-docker username is rpi
    container_name: stryderx-robot
    tty: true
    stdin_open: true
    command: /bin/bash
    network_mode: host
