FROM jrendon514/robot-base-docker:humble-v0.2.0

# Elevate to root for setup.
USER root

# Workspace for StryderX ROS2 packages
RUN mkdir -p /home/rpi/stryderx /home/rpi/.cache/pre-commit && \
chown -R rpi:rpi /home/rpi/stryderx /home/rpi/.cache

RUN wget -qO /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-arm64 && \
chmod a+x /usr/local/bin/hadolint

RUN apt-get update && apt-get install -y --no-install-recommends \
clang=1:14.0* \
clang-format=1:14.0* \
doxygen=1.9.1* \
git=1:2.34.1* \
graphviz=2.42.2* \
python3-pip=22.0.2* \
python3-serial=3.5-1* \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir pre-commit==3.5.0

COPY vendor/rosmaster_lib_v3 /tmp/rosmaster_lib_v3
WORKDIR /tmp/rosmaster_lib_v3
RUN python3 setup.py install && \
rm -rf /tmp/rosmaster_lib_v3

ARG APP_VERSION=DEV
ARG GIT_COMMIT_HASH="unknown"
ARG BUILD_DATE="unknown"

LABEL org.opencontainers.image.authors="Julian A. Rendon" \
    org.opencontainers.image.source="https://github.com/STRYDER-X/stryderX" \
    org.opencontainers.image.description="Docker image for STRYDER-X ROS2 Humble" \
    org.opencontainers.image.licenses="GPLv3" \
    org.opencontainers.image.version="${APP_VERSION}" \
    org.opencontainers.image.revision="${GIT_COMMIT_HASH}" \
    org.opencontainers.image.created="${BUILD_DATE}"

WORKDIR /home/rpi/stryderx
USER rpi

CMD ["/bin/bash"]
