FROM jrendon514/robot-base-docker:humble-v0.1.1

LABEL org.opencontainers.image.authors="Julian A. Rendon" \
    org.opencontainers.image.source="https://github.com/STRYDER-X/stryderX" \
    org.opencontainers.image.description="Docker image for STRYDER-X ROS2 Humble" \
    org.opencontainers.image.licenses="GPLv3"
