pipeline {
    agent {
        dockerfile {
            filename 'stryderx_docker/Dockerfile'
            dir '.'
            reuseNode true
            label 'StryderX'
        }
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
        ansiColor('xterm')
    }

    stages {
        stage('Lint') {
            steps {
                sh 'make lint'
            }
        }

        stage('Build') {
            steps {
                sh 'make build'
            }
        }

        stage('Test') {
            steps {
                sh 'make test'
            }
        }

    }

    post {
        always {
            node(env.NODE_NAME) {
                sh 'make report'
            }
        }
    }
}
