pipeline {
    agent {
        dockerfile {
            filename 'stryderx_docker/Dockerfile'
            dir '.'
            reuseNode true
            label "${params.AGENT}"
        }
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
        ansiColor('xterm')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '10'))
    }

    parameters {
        choice(
            name: 'AGENT',
            choices: ['StryderX-Core', 'Linux'],
            description: 'Select the specific Agent for this to run on.'
        )
    }

    stages {
        stage('Lint') {
            steps {
                sh 'make lint'
            }
        }

        stage('Build') {
            steps {
                sh 'make build'
            }
        }

        stage('Test') {
            steps {
                sh 'make test'
            }
        }

        stage('Docs') {
            when {
                branch 'main'
            }
            steps {
                sh 'make docs'
                archiveArtifacts artifacts: 'build/stryderx_hardware/docs/html/**', allowEmptyArchive: false
            }
        }
    }

    post {
        always {
            sh 'make report || true'
            archiveArtifacts artifacts: 'log/test_report.log', allowEmptyArchive: true
            junit testResults: 'build/**/test_results/**/*.xml', allowEmptyResults: true
        }

        cleanup {
            cleanWs(deleteDirs: true, disableDeferredWipeout: true, notFailBuild: true)
        }
    }
}
